apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: {{ .Values.job }}
        image: alpine
        args: {{ .Values.cmd }}
      restartPolicy: Never
